# action.yml
name: "CDK action"
description: "CDK action"
inputs:
  tags:
    description: "Docker image tags"
    required: true
  context:
    description: "Context for the docker build"
    required: false
  dockerfile:
    description: "The dockerfile. Default: Dockerfile"
    required: false
  create_repo:
    description: "Whether to create the repo if not exist. Default: null"
    required: false
outputs:
  ouptut:
    description: "The command output"
runs:
  using: "docker"
  image: "Dockerfile"