name: ECR
on:
  push:
    paths:
      - "../frontend/**"
  schedule:
    - cron: 37 * * * *
  workflow_dispatch: {}

jobs:
  cdk_job:
    runs-on: ubuntu-latest
    name: ECR public action
    steps:
      - name: Get repo name
        id: repoName
        run: echo "::set-output name=reponame::$(echo ${{github.repository}} | cut -d '/' -f 2)"
      - name: Get short SHA
        id: sha
        run: echo "::set-output name=sha7::$(echo ${GITHUB_SHA} | cut -c1-7)"
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Build and Push to ECR public
        id: build-and-push
        uses: pahud/ecr-public-action@8cd826db40befb59b0cd0b60b22a7ba72d06a7f7
        with:
          tags: |
            public.ecr.aws/u6c8v2b2/multici:latest
            public.ecr.aws/u6c8v2b2/multici:${{ steps.sha.outputs.sha7 }}
