# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
 
 
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
   build-and-publish:
    name: build and publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      -
        name: Login to Public ECR
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry: public.ecr.aws
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: public.ecr.aws
          ECR_REPOSITORY: multici
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t deploy .
          docker tag deploy:latest public.ecr.aws/u6c8v2b2/multici:latest
          docker push public.ecr.aws/u6c8v2b2/multici:latest
          echo "::set-output name=image::public.ecr.aws/u6c8v2b2/multici:latest"
